# Generated by Django 5.0.3 on 2024-07-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assistant',
            field=models.BooleanField(default=False, verbose_name='Est un assistant'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_charger_programme',
            field=models.BooleanField(default=False, verbose_name='Est un chargé de programme'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_charger_projet',
            field=models.BooleanField(default=False, verbose_name='Est un chargé de projet'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_responsable',
            field=models.BooleanField(default=False, verbose_name='Est un responsable de suivi'),
        ),
    ]
