# Generated by Django 5.0.3 on 2024-05-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_infosgenerale_groupe_cible_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosgenerale',
            name='total_pers_femme',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infosgenerale',
            name='total_pers_homme',
            field=models.IntegerField(default=0),
        ),
    ]
