# Generated by Django 5.0.3 on 2024-05-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_titreactivite_domaine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, null=True)),
                ('impot', models.IntegerField(default=0)),
                ('cotisation', models.IntegerField(default=0)),
                ('autre_contribution', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('date_realisation', models.CharField(max_length=50, null=True)),
                ('nom_cabinet', models.CharField(max_length=50, null=True)),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_situation', to='services.situation')),
            ],
        ),
    ]
