# Generated by Django 5.0.3 on 2024-05-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_situation_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='id_secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_secteur', to='services.secteur'),
        ),
        migrations.AddField(
            model_name='activiteplu',
            name='id_secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_secteur_plus', to='services.secteur'),
        ),
    ]
