# Generated by Django 5.0.3 on 2024-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_situation_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='titre',
            new_name='titre_test',
        ),
    ]
