# Generated by Django 5.0.3 on 2024-05-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_rename_titre_audit_titre_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='titre_test',
            field=models.CharField(default='titre', max_length=50, null=True),
        ),
    ]
