# Generated by Django 5.0.3 on 2024-05-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_alter_audit_titre_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audit',
            name='titre_test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
