# Generated by Django 5.0.3 on 2024-05-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_situation_total_alter_audit_titre_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfosSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('date_debut', models.CharField(max_length=50, null=True)),
                ('date_fin', models.CharField(max_length=50, null=True)),
                ('cout', models.IntegerField(default=0)),
                ('objectifs_principals', models.CharField(max_length=100)),
                ('benef_direct_homme', models.IntegerField(default=0)),
                ('benef_direct_femme', models.IntegerField(default=0)),
                ('resultats', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='partenaire',
            name='id_infos_specifique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='infos_specific', to='services.infosspecific'),
        ),
    ]
