# Generated by Django 5.0.3 on 2024-06-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_infosspecific_utilisateur_alter_audit_nom_cabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultats', models.CharField(max_length=100, null=True)),
                ('id_specific', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_specific', to='services.infosspecific')),
            ],
        ),
    ]
