# Generated by Django 5.0.3 on 2024-06-05 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='id_infos_specifique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_specific_infos', to='services.infosspecific'),
        ),
    ]
