# Generated by Django 5.0.3 on 2024-06-05 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0045_objectif_id_infos_specifique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosspecific',
            name='resultats',
        ),
    ]
