# Generated by Django 5.0.3 on 2024-07-04 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_alter_infosspecific_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosspecific',
            name='id_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_projet_specific', to='services.projet'),
        ),
    ]
