# Generated by Django 5.0.3 on 2024-07-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0048_infosspecific_id_projet'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteplu',
            name='id_activite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_activites', to='services.activite'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='resultats',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
