# Generated by Django 5.0.3 on 2024-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_activiteplu_id_activite_alter_resultat_resultats'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteplu',
            name='planifier',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
