# Generated by Django 5.0.3 on 2024-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0050_activiteplu_planifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='periode_prevue_debut',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='periode_prevue_fin',
            new_name='paroisse',
        ),
        migrations.RenameField(
            model_name='activite',
            old_name='responsable',
            new_name='province',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='budget_total',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='part_burkina',
        ),
        migrations.AddField(
            model_name='activite',
            name='contribution_beneficiaire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='contribution_partenaire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='cout_realisation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='region',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='total_benef_direct',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='activite',
            name='quantite_prevue',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
