# Generated by Django 5.0.3 on 2024-07-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_rename_periode_prevue_debut_activite_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='partenaires',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
