# Generated by Django 5.0.3 on 2024-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_activite_partenaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='activiteplu',
            name='partenaires',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
