# Generated by Django 5.0.3 on 2024-07-09 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_activiteplu_partenaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='id_activiteplus',
        ),
        migrations.AddField(
            model_name='activite',
            name='planifier',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=50, null=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('region', models.CharField(max_length=50, null=True)),
                ('paroisse', models.CharField(max_length=50, null=True)),
                ('titre', models.CharField(max_length=100, null=True)),
                ('unite_physique', models.CharField(max_length=50, null=True)),
                ('quantite_prevue', models.IntegerField(default=0)),
                ('periode_prevue_debut', models.CharField(max_length=50, null=True)),
                ('periode_prevue_fin', models.CharField(max_length=50, null=True)),
                ('responsable', models.CharField(max_length=50, null=True)),
                ('cout_realisation', models.IntegerField(default=0)),
                ('contribution_beneficiaire', models.IntegerField(default=0)),
                ('contribution_partenaire', models.IntegerField(default=0)),
                ('partenaires', models.CharField(max_length=100, null=True)),
                ('part_burkina', models.IntegerField(default=0)),
                ('total_benef_direct', models.IntegerField(default=0)),
                ('nbre_benef_direct_homme', models.IntegerField(default=0)),
                ('nbre_benef_direct_femme', models.IntegerField(default=0)),
                ('realisation', models.CharField(max_length=10, null=True)),
                ('id_activite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_activites', to='services.activite')),
                ('id_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_projet_plus', to='services.projet')),
                ('id_secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_secteur_plus', to='services.secteur')),
                ('id_sous_secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_sous_secteur_plus', to='services.soussecteur')),
                ('id_titre_activites', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_titre_activite_plus', to='services.titreactivite')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='partenaire',
            name='id_realisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_realisation', to='services.realisation'),
        ),
        migrations.DeleteModel(
            name='ActivitePlu',
        ),
    ]
