# Generated by Django 5.0.3 on 2024-07-09 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_remove_partenaire_id_activiteplus_activite_planifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titreactivite',
            name='unite_physique',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='id_titre_activites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_titre_realisation', to='services.titreactivite'),
        ),
    ]
