# Generated by Django 5.0.3 on 2024-07-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_titreactivite_unite_physique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='realiser',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
