# Generated by Django 5.0.3 on 2024-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_realisation_realiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activite',
            old_name='planifier',
            new_name='planification',
        ),
        migrations.RemoveField(
            model_name='realisation',
            name='realiser',
        ),
    ]
