# Generated by Django 5.0.3 on 2024-07-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_rename_planifier_activite_planification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosspecific',
            name='cout',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
