# Generated by Django 5.0.3 on 2024-07-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0058_alter_infosspecific_cout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosspecific',
            name='benef_direct_femme',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='infosspecific',
            name='benef_direct_homme',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='infosspecific',
            name='objectifs_principals',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
