# Generated by Django 5.0.3 on 2024-07-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0059_alter_infosspecific_benef_direct_femme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosspecific',
            name='partenaires',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
