# Generated by Django 5.0.3 on 2024-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_infosspecific_partenaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='nbre_benef_direct_femme',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='activite',
            name='nbre_benef_direct_homme',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
