# Generated by Django 5.0.3 on 2024-07-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0061_activite_nbre_benef_direct_femme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='part_burkina',
        ),
    ]
