# Generated by Django 5.0.3 on 2024-07-18 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_remove_realisation_part_burkina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salaire', models.IntegerField(default=0)),
                ('carburant_entretien', models.IntegerField(default=0)),
                ('frais_communication', models.IntegerField(default=0)),
                ('acquisition_materiel', models.IntegerField(default=0)),
                ('rencontre_equipe', models.IntegerField(default=0)),
                ('contribution_electrique_eau', models.IntegerField(default=0)),
                ('achat_consommable', models.IntegerField(default=0)),
                ('entretien_locaux', models.IntegerField(default=0)),
                ('maintenance_appareil', models.IntegerField(default=0)),
                ('expedition_courier', models.IntegerField(default=0)),
                ('frais_bancaire', models.IntegerField(default=0)),
                ('cout_indirect', models.IntegerField(default=0)),
                ('id_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_projet_depense', to='services.projet')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_depense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
