# Generated by Django 5.0.3 on 2024-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0063_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosspecific',
            name='total_benef_direct',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
