# Generated by Django 5.0.3 on 2024-10-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0064_infosspecific_total_benef_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosspecific',
            name='id_secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_secteur_activite_specific', to='services.secteur'),
        ),
        migrations.AddField(
            model_name='infosspecific',
            name='id_sous_secteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_sous_secteur_activite_specific', to='services.soussecteur'),
        ),
        migrations.AddField(
            model_name='infosspecific',
            name='id_titre_activites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_titre_activite_specific', to='services.titreactivite'),
        ),
    ]
