# Generated by Django 5.0.3 on 2024-10-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0065_infosspecific_id_secteur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depense',
            old_name='achat_consommable',
            new_name='consommable_divers',
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='acquisition_materiel',
            new_name='equipement_materiel',
        ),
        migrations.RenameField(
            model_name='depense',
            old_name='carburant_entretien',
            new_name='salaire_avantages',
        ),
        migrations.RenameField(
            model_name='infosspecific',
            old_name='cout',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='contribution_electrique_eau',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='cout_indirect',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='entretien_locaux',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='expedition_courier',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='frais_bancaire',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='frais_communication',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='maintenance_appareil',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='rencontre_equipe',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='salaire',
        ),
        migrations.AddField(
            model_name='infosspecific',
            name='depense_globale',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='realisation',
            name='nbre_benef_jeune_femme',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='realisation',
            name='nbre_benef_jeune_homme',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='realisation',
            name='total_benef_jeune',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='AutreDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100, null=True)),
                ('prix', models.IntegerField(default=0)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_autre_depense', to='services.depense')),
            ],
        ),
    ]
