# Generated by Django 5.0.3 on 2024-10-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0066_rename_achat_consommable_depense_consommable_divers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
