# Generated by Django 5.0.3 on 2024-10-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0067_listpartenaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='part_burkina',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
